name: changelog

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled, reopened]

permissions:
  contents: read

jobs:
  build:
    name: Changelog Entry Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-regex-match@v2
        name: Check PR description for changelog content
        if:
          contains(github.event.pull_request.labels.*.name, 'skip news :mute:') != true
        with:
          text: ${{ github.event.pull_request.body }}
          regex: '<!-- changelog start -->\n(.*\n)*<!-- changelog end -->'
          flags: gm
